#!/usr/bin/env python3
"""
Generate docs/boards/FIRMWARE_EXERCISE_MATRIX.md from
validation/firmware_exercise.yaml.

Companion to scripts/generate_validation_status.py. That script answers "is the
model right vs silicon?"; this one answers the complementary question "does any
real firmware actually RUN against the model?" — surfacing peripherals that are
modeled but never exercised (unit-only / dead), and stubs that masquerade as
models (shim). The matrix makes the firmware-exercise gap visible and gateable
so dead/shim cells cannot silently accumulate.

Modes
-----
  (default)   regenerate docs/boards/FIRMWARE_EXERCISE_MATRIX.md in place
  --check     regenerate to memory and diff against the committed file; exit 1
              if they differ (run this in CI so the doc cannot go stale)

Needs PyYAML (pip install pyyaml).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: PyYAML required — `pip install pyyaml`", file=sys.stderr)
    sys.exit(2)

CORE_ROOT = Path(__file__).resolve().parent.parent
MANIFEST = CORE_ROOT / "validation" / "firmware_exercise.yaml"
OUT_DOC = CORE_ROOT / "docs" / "boards" / "FIRMWARE_EXERCISE_MATRIX.md"

GATE_BADGE = {
    "pr": "🟢 PR gate",
    "release": "🟡 release CI",
    "ignored": "🟠 on-demand",
    "none": "⚪ ungated",
}


def dead_count(chip: dict) -> int:
    d = chip.get("dead") or {}
    return int(d.get("count", 0))


def shim_list(chip: dict) -> list:
    return chip.get("shim") or []


def proven_list(chip: dict) -> list:
    return chip.get("proven") or []


def unit_list(chip: dict) -> list:
    return chip.get("unit_only") or []


def strongest_gate(chip: dict) -> str:
    """Best (most-trusted) gate across this chip's proven peripherals."""
    order = ["pr", "release", "ignored", "none"]
    gates = [p.get("gate", "none") for p in proven_list(chip)]
    for g in order:
        if g in gates:
            return g
    return "none"


def render(manifest: dict) -> str:
    chips = manifest["chips"]
    L: list[str] = []
    L.append(
        "<!-- GENERATED by scripts/generate_firmware_exercise_matrix.py — DO NOT EDIT BY HAND."
    )
    L.append(
        "     Source of truth: validation/firmware_exercise.yaml. Regenerated and gated on every CI run. -->"
    )
    L.append("")
    L.append("# Firmware-exercise matrix")
    L.append("")
    L.append(
        "Machine-generated from `validation/firmware_exercise.yaml`. Where "
        "`VALIDATION_STATUS.md` asks *\"is the model right vs silicon?\"*, this "
        "matrix asks the complementary question: **does a real booting firmware "
        "actually RUN against the model?**"
    )
    L.append("")
    L.append("**The bar (strict):** a model is `proven` only when a booting firmware drives it "
             "end to end. A banner-only boot that never touches the peripheral, or a unit test "
             "that pokes its registers without running firmware, does **not** count.")
    L.append("")
    L.append("Classes: **proven** (firmware drives it) · **unit-only** (register test, no firmware) "
             "· **dead** (modeled, never run) · **shim** (hardcoded stub masquerading as a model — "
             "the most misleading class).")
    L.append("")
    L.append("Gate of the strongest proving firmware: " + " · ".join(GATE_BADGE.values()) + ".")
    L.append("")
    L.append("| Chip | Arch | Proven | Unit-only | Dead | Shim | Strongest gate |")
    L.append("|------|------|--------|-----------|------|------|----------------|")
    tot_proven = tot_unit = tot_dead = tot_shim = 0
    for c in chips:
        np = len(proven_list(c))
        nu = len(unit_list(c))
        nd = dead_count(c)
        ns = len(shim_list(c))
        tot_proven += np
        tot_unit += nu
        tot_dead += nd
        tot_shim += ns
        gate = GATE_BADGE.get(strongest_gate(c), "—")
        L.append(
            f"| `{c['id']}` | {c.get('arch','?')} | {np} | {nu} | {nd} | {ns} | {gate} |"
        )
    L.append(
        f"| **total** | | **{tot_proven}** | **{tot_unit}** | **{tot_dead}** | **{tot_shim}** | |"
    )
    L.append("")
    L.append(
        f"> {tot_proven} peripheral models are driven by real firmware; "
        f"{tot_unit} are register-tested only; {tot_dead} are modeled but never run; "
        f"**{tot_shim} are shims** (hardcoded stubs presenting as models)."
    )
    L.append("")

    for c in chips:
        L.append(f"## `{c['id']}` — {c.get('arch','?')}")
        L.append("")
        if c.get("headline"):
            L.append(f"_{c['headline']}_")
            L.append("")
        proven = proven_list(c)
        if proven:
            L.append("**Proven by running firmware:**")
            L.append("")
            L.append("| Peripheral | Firmware | Evidence | Gate |")
            L.append("|------------|----------|----------|------|")
            for p in proven:
                badge = GATE_BADGE.get(p.get("gate", "none"), p.get("gate", "?"))
                L.append(
                    f"| {p['p']} | `{p.get('fw','?')}` | {p.get('ev','')} | {badge} |"
                )
            L.append("")
        if unit_list(c):
            L.append("**Unit-only** (register test, no firmware drives it): "
                     + ", ".join(f"`{u}`" for u in unit_list(c)))
            L.append("")
        d = c.get("dead") or {}
        if dead_count(c) or d.get("examples"):
            ex = ", ".join(f"`{e}`" for e in d.get("examples", []))
            line = f"**Dead** ({dead_count(c)} modeled but never exercised)"
            if ex:
                line += f": {ex}"
            L.append(line)
            if d.get("note"):
                L.append("")
                L.append(f"  > ⚠ {d['note']}")
            L.append("")
        if shim_list(c):
            L.append("**Shims** (hardcoded stubs — not real fidelity):")
            L.append("")
            for s in shim_list(c):
                note = f" — {s['note']}" if s.get("note") else ""
                L.append(f"- `{s['p']}` ({s.get('ev','')}){note}")
            L.append("")
    return "\n".join(L).rstrip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="fail if committed doc is stale")
    args = ap.parse_args()

    manifest = yaml.safe_load(MANIFEST.read_text())
    rendered = render(manifest)

    if args.check:
        existing = OUT_DOC.read_text() if OUT_DOC.exists() else ""
        if existing != rendered:
            print(
                f"ERROR: {OUT_DOC.relative_to(CORE_ROOT)} is out of date.\n"
                "       Run: python3 scripts/generate_firmware_exercise_matrix.py",
                file=sys.stderr,
            )
            return 1
        return 0

    OUT_DOC.write_text(rendered)
    print(f"wrote {OUT_DOC.relative_to(CORE_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
